[package]
name = "ntbk"
version = "0.1.0"
authors = ["Maas Lalani <maaslalani1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.6.2"
dirs = "3.0.0"
